name: Post Positive News About India

on:
  schedule:
    - cron: '0 4 * * *'   # 9:30 AM IST
    - cron: '0 16 * * *'  # 9:30 PM IST
  workflow_dispatch:  # Allow manual trigger

jobs:
  post_news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Debug LOG_LEVEL
        run: echo "LOG_LEVEL is set to $LOG_LEVEL"
        env:
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}

      - name: Run the bot
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_SECRET: ${{ secrets.TWITTER_ACCESS_SECRET }}
          LOG_LEVEL: ${{ vars.LOG_LEVEL }}  # Pass LOG_LEVEL to the script
        run: python main.py
